// constants.js

export const FETCH_CART_ITEMS_REQUEST = 'FETCH_CART_ITEMS_REQUEST';
export const FETCH_CART_ITEMS_SUCCESS = 'FETCH_CART_ITEMS_SUCCESS';
export const FETCH_CART_ITEMS_FAILURE = 'FETCH_CART_ITEMS_FAILURE';
export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';
export const REMOVE_ITEM_REQUEST = 'REMOVE_ITEM_REQUEST';
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
export const REMOVE_ITEM_FAILURE = 'REMOVE_ITEM_FAILURE';
export const  CLEAR_CART = ' CLEAR_CART';
export const UPDATENUM_ITEM_REQUEST = 'UPDATENUM_ITEM_REQUEST';
export const UPDATENUM_ITEM_SUCCESS = 'UPDATENUM_ITEM_SUCCESS';
export const UPDATENUM_ITEM_FAILURE = 'RUPDATENUM_ITEM_FAILURE';
export const  FETCH_ADDRESS_ID = 'FETCH_ADDRESS_ID';
export const FETCH_NEW_ORDER_REQUEST = 'FETCH_NEW_ORDER_REQUEST';
export const FETCH_NEW_ORDER_SUCCESS = 'FETCH_NEW_ORDER_SUCCESS';
export const FETCH_NEW_ORDER_FAILURE = 'FETCH_NEW_ORDER_FAILURE';
